services:
  web:
    container_name: web_container
    image: node:16.15.1
    environment: 
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - MONGO_CONNECTION_STRING=mongodb://mongodb:27017/dev-store
    volumes:
      - ./src:/src
    ports:
      - 3000:3000
      - 3001:3001
    working_dir: /src
    command: npm run dev

  mongodb:
    image: mongo:5.0
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017